### ISSUE TITLE
请教个问题

### ISSUE THREAD

**Issue by imkz** [iduzui/optica#1]
![image](https://user-images.githubusercontent.com/18732636/35844529-fd84e1cc-0b48-11e8-982f-bc3355b426e4.png)

你好，请问一下这是什么问题，www.imkz.space 点击分类没反应。

**Comment by iduzui** [comment]
我在你的博客留言过，之前引用的js路径写死了，昨天修改过了。你可以下载最新的模板文件，只需要替换footer.php这个文件就可以了。

**Comment by imkz** [comment]
刚才上传文件有问题，覆盖文件解决了，多谢。

**Comment by iduzui** [comment]
没事，有问题可以继续提交issue或者直接去我博客留言。
